apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp
 namespace: dev
spec:
 replicas: 1
 selector:
   matchLabels:
     app: myapp
 template:
   metadata:
     labels:
       app: myapp
   spec:
     containers:
     - name: myapp
       image: sudhaacr001.azurecr.io/myapp:v1
       ports:
       - containerPort: 5000
       env:
       - name: ENV_NAME
         value: "Development"